# Colors from global-colors.css
cursor #C0CAF5
cursor_text_color #1A1B26

foreground            #C0CAF5
background            #1A1B26
selection_foreground  #1A1B26
selection_background  #7AA2F7
url_color             #7DCFFF

# black
color0   #1A1B26
color8   #414868

# red
color1   #F7768E
color9   #F7768E

# green
color2   #9ECE6A
color10  #9ECE6A

# yellow
color3   #E0AF68
color11  #E0AF68

# blue
color4   #7AA2F7
color12  #7AA2F7

# magenta
color5   #BB9AF7
color13  #BB9AF7

# cyan
color6   #7DCFFF
color14  #7DCFFF

# white
color7   #C0CAF5
color15  #C0CAF5
