# Global color definitions - from ~/.config/themes/global-colors.css
# bg_color = #1A1B26
# fg_color = #C0CAF5
# tray_color = #414868
# accent_color = #9ECE6A
# highlight_color = #7AA2F7
# urgent_color = #F7768E

general {
    col.active_border = rgba(7AA2F7AA)
    col.inactive_border = rgba(414868AA)
}

misc {
    background_color = rgba(1A1B26FF)
}

plugin {
    hyprbars {
        # Honestly idk if it works like css, but well, why not
        bar_text_font = Rubik, Geist, AR One Sans, Reddit Sans, Inter, Roboto, Ubuntu, Noto Sans, sans-serif
        bar_height = 30
        bar_padding = 10
        bar_button_padding = 5
        bar_precedence_over_border = true
        bar_part_of_window = true

        bar_color = rgba(7AA2F7AA)
        col.text = rgba(C0CAF5FF)


        # example buttons (R -> L)
        #hyprbars-button = color, size, on-click
        hyprbars-button = rgba(7AA2F7FF), 13, 󰖭, hyprctl dispatch killactive
        hyprbars-button = rgba(7AA2F7FF), 13, 󰖯, hyprctl dispatch fullscreen 1
        hyprbars-button = rgba(7AA2F7FF), 13, 󰖰, hyprctl dispatch movetoworkspacesilent special
    }
}

windowrulev2 = bordercolor rgba(7AA2F7AA) rgba(414868AA),pinned:1
